# TODO:
#   FOLLOW THE USER INPUT:
#       IF THE INPUT IS INCORRECT WITH THE TEXT MARK THE WRONG LETTERS WITH RED
#       IF THE INPUT IS CORRECT WITH THE TEXT MARK CORRECT LETTERS WITH GREEN
#
# DONE:
#   READ RANDOM AMOUNT OF SENTENCES FROM RANDOM LINE IN A TEXT FILE (MAX 7SENTENCES MIN 3)
#   SHOW THE TEXT TO READ IT
#   BLOCK AN INPUT FROM A USER TILL THE END OF COUNTDOWN/PRESSING A BUTTON
#   ADD A COUNTDOWN/START BUTTON THAT STARTS AND LETS YOU TYPE
#   AFTER FINISHING LAST WORD CALCULATE HOW MUCH TIME IT TOOK THE USER TO FINISH AND CALCULATE WORDS/MIN



